### ISSUE TITLE
consistency followFeed

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-php#10]
python, js and ruby do it like this

Get the feed object for aggregated 3 and follow user 1

aggregated3 = client.feed('aggregated:3')
aggregated3.follow('user:1')

vs

// Get the feed object for aggregated 3 and follow user 1
$aggregated3 = $client->feed('aggregated:3');
$aggregated3->followFeed('user:1');

**Comment by iandouglas** [comment]
This idea is almost two years old, but it would be nice to be consistent across our libraries. This would introduce a breaking change, so we'd want to version accordingly.

**Comment by tbarbugli** [comment]
what about we keep `follow` and `followFeed` for a few versions and then remove the old one?

**Comment by hannesvdvreken** [comment]
Noted. We can make `followFeed` an alias of `follow` and mark it `followFeed` as deprecated and remove it in the next major version.
