### ISSUE TITLE
Time Parameter For Batch Methods

### ISSUE THREAD

**Issue by NaingAungLu** [GetStream/stream-php#101]
My Acitity 
foreign_id - activity:1
time       - 2021-04-04T05:47:16.065221Z

$results = $this->client->getActivities(null, [[
    'activity:1',
    Carbon::parse("2021-04-04T05:47:16.065221Z"),
]]);

If i pass time as "2021-04-04T05:47:16.065221Z", I got "Call to a member function format() on string" error.
So i pass like that "Carbon::parse("2021-04-04T05:47:16.065221Z")"
But i can't get activity because of the wrong time.

I see getstream php library format the time like that.
$times[] = $fit[1]->format(DateTime::ISO8601);
It returns 2021-04-04T10:27:25+0000

If i change your code like below, i can retrieve.
$times[] = $fit[1]->format('Y-m-d\TH:i:s.u');

gz#10834

**Comment by ferhatelmas** [comment]
Thanks for the different ways of doing it. What is the actual question here ?

**Comment by ferhatelmas** [comment]
@NaingAungLu resolution matters. With carbon case, you're passing more granular time for a truncated time before (while creating activity via SDK) since they don't match you can't get it back.

I will close this but let me know if there is still a confusion.
