### ISSUE TITLE
Missing GetStream\Stream\Feed::delete() function

### ISSUE THREAD

**Issue by everydaypanos** [GetStream/stream-php#106]
Hi,

Although in the README file there is a $userFeed->delete() function, it does not exist in the GetStream\Stream\Feed class.

Thanks.

gz#13126

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/13126'>Zendesk ticket #13126</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and get back to you soon.

Best,
<br><p><em><small>°°°</small></em></p>

**Comment by ferhatelmas** [comment]
@everydaypanos This endpoint was discontinued so long ago but readme kept its legacy. Removed it now.
