### ISSUE TITLE
Attempted to call function "parse_query"

### ISSUE THREAD

**Issue by TheFox** [GetStream/stream-php#107]
I am getting this error

```
Attempted to call function "parse_query" from namespace "GuzzleHttp\Psr7".
```

I guess I am running the correct versions of Guzzle:

```
/app# composer info | grep guzzle
guzzlehttp/guzzle                        7.3.0     Guzzle is a PHP HTTP c...
guzzlehttp/promises                      1.4.1     Guzzle promises library
guzzlehttp/psr7                          2.0.0     PSR-7 message implemen...
```

The [PSR7 Repo](https://github.com/guzzle/psr7#upgrading-from-function-api) says that the `parse_query` has been replaced by `Query::parse`.

**Comment by alexhansonsmith** [comment]
@TheFox  - did you manage to find a fix for this? We are experiencing the same issue.

**Comment by ferhatelmas** [comment]
https://github.com/GetStream/stream-php/releases/tag/5.1.1 should fix. Let me know please.

**Comment by TheFox** [comment]
For the people who (for whatever reason) cannot upgrade to the fix version. This is what I did in the meanwhile:

In `composer.json`:

```json
...
    "autoload": {
        ...
        "files": [
            "extension/guzzle.php"
        ]
    },
    "autoload-dev": {
        ...
        "files": [
            "extension/guzzle.php"
        ]
    },
...
```

```php
<?php

// extension/guzzle.php

namespace GuzzleHttp\Psr7;

function parse_query(string $str, $urlEncoding = true): array
{
    return Query::parse($str, $urlEncoding);
}
```

/cc @alexhansonsmith

**Comment by ferhatelmas** [comment]
@TheFox 👍🏻 nice workaround, thanks for sharing.
