### ISSUE TITLE
All tests are failing

### ISSUE THREAD

**Issue by araines** [GetStream/stream-php#28]
I actually get different test failures/errors when I've pulled it to run it locally, which is interesting.  But either way, CI isn't much use if tests fail all the time.

**Comment by tschellenbach** [comment]
Unfortunately some of our client libraries use integration testing, which is just very unreliable for an asynchronous system. We're working on it :)

**Comment by araines** [comment]
Ah I did see that in the tests when I eyeballed them, but I assumed it wasn't connecting to real services!  This makes a lot more sense now as to why it wouldn't work very well :)

Given I've been writing some integration tests stubbing Stream out, if I get a chance I'll take a look at trying to port some of our tests over to help out with the library.

**Comment by tschellenbach** [comment]
Awesome, that would be much appreciated!
