### ISSUE TITLE
Error dsiplay while connecting from client to server in zimbra api

### ISSUE THREAD

**Issue by aiyappann** [GetStream/stream-php#32]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error response [url] https://10.10.2.32:7071/service/admin/soap [status code] 500 [reason phrase] Server Error' in /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/ in /home/vikatan/www/intrasite/intra.vikatan.com/zimbra/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89

Please help me all.

**Comment by tbarbugli** [comment]
can you add more information about this? can you add a full stack trace and
some more detail about the problem?

**Comment by iandouglas** [comment]
@aiyappann can you contact us at support@getstream.io for assistance with this, or let us know that you've resolved this?

**Comment by dwightgunning** [comment]
@hannesvdvreken suggest a quick check but looks like this can be closed.

**Comment by hannesvdvreken** [comment]
Looks like a server-side problem with a service not related to this SDK.
