### ISSUE TITLE
ERROR - The request could not be satisfied

### ISSUE THREAD

**Issue by MadTiago** [GetStream/stream-php#34]
> Type: GetStream\Stream\StreamFeedException
> Message: ERROR The request could not be satisfied (bad request)
> 
> Generated by cloudfront (CloudFront)
> 
> Filename: .../vendor/get-stream/stream/lib/GetStream/Stream/Feed.php
> Line Number: 102

I'm getting this exception when fetching some activities on testing setup (ubuntu, apache 2.4.7, php 7.0.8)
The same code works fine on my local setup (windows, xampp -> php 7.0.6)

**Comment by tbarbugli** [comment]
what version of the client are you using?

**Comment by MadTiago** [comment]
I forgot to change the bind address on test vps.
Changing it to listen on all interfaces rather than 127.0.0.1 fixed it.
