### ISSUE TITLE
Support for php-jwt v3

### ISSUE THREAD

**Issue by actuallymab** [GetStream/stream-php#35]
Hi there,

Anybody thinking on giving support for php-jwt ~3.0?

**Comment by tbarbugli** [comment]
good point, we currently support a fairly old version of the jwt lib. Did you have the chance to try the client on 3.x or 4.x?

**Comment by actuallymab** [comment]
No, I haven't. I may try it tomorrow. I think there might be a couple of lines needs to be changed, but I'm not sure yet cause I'm out of office right now.

**Comment by tbarbugli** [comment]
@actuallymab did you have a chance to look into this?

**Comment by mandersondesign** [comment]
I would love an update on this. We can't install get-stream because one of our other packages require jwt 3.0.0.

**Comment by mandersondesign** [comment]
update: i just issued a PR for this update. I tested it with a few calls, but maybe not as thoroughly as y'all would like. Maybe put it through the wringer?

**Comment by Sopamo** [comment]
This needs to happen for us to be able to use stream at all. I don't have the resources to do a thorough test atm but maybe someone from @GetStream has.

**Comment by tbarbugli** [comment]
the client on master branch is now using php-jwt ~3.0. We are going to give it more testing and release it. In the meantime, you can install the library from github instead of packagist

**Comment by iandouglas** [comment]
We now support JWT 3 and 4
