### ISSUE TITLE
Calling updateActivities with an empty array causes an error

### ISSUE THREAD

**Issue by araines** [GetStream/stream-php#40]
Not sure if this is desired behaviour or not, but our assumption was that calling `Client::updateActivities` with an empty array would be a no-op rather than making an HTTP call which subsequently fails.

**Comment by tbarbugli** [comment]
I guess it makes sense to silently exit without doing any API calls if the activities parameter is an empty array. We'll add this to our next release cycle.

**Comment by hannesvdvreken** [comment]
@araines could you verify if #51 and its included test case would fix your problem?

**Comment by araines** [comment]
@hannesvdvreken I'm afraid we're no longer using this project, but the code change looks like it should do what I was expecting. 👍
