### ISSUE TITLE
ERROR - The request could not be satisfied same as MaxTiago's 

### ISSUE THREAD

**Issue by imonoid** [GetStream/stream-php#50]
Hi Guys, 

I am getting this cloudfront error similar to MaxTiago's.  But I can't seem to fix it.  I am assuming, based on MaxTiago's comment, that we need to have our VPS server bind to listen all:

	listen-on { any; };
	listen-on-v6 { any; };

but it is still not working.  Works perfectly on my local machine (XAMPP) as well as our test server in Heroku, but not on our VPS server.

**Comment by imonoid** [comment]
Hi never mind this issue.  Its already fixed.  The issue was caused by php curl not being installed or updated to 5.6.

**Comment by dwightgunning** [comment]
Glad to hear it was just a minor environment issue. Thanks.
