### ISSUE TITLE
Guzzle 6.0 Issue

### ISSUE THREAD

**Issue by nuttyroll** [GetStream/stream-php#58]
Message: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /vendor/guzzlehttp/guzzle/src/Client.php on line 87 and defined

**Comment by hannesvdvreken** [comment]
Hi!

Which version of this package do you have installed?

**Comment by hannesvdvreken** [comment]
Obviously called here: https://github.com/guzzle/guzzle/blob/master/src/Client.php#L87 but I'd like to figure out if it's cause by this package or maybe something on your end.

**Comment by nuttyroll** [comment]
Hi,

I was able to solve the issue by updating the plugin. Thanks a lot for your prompt reply.

**Comment by hannesvdvreken** [comment]
you're welcome!
