### ISSUE TITLE
'Invalid Json Payload' error on updateActivities()

### ISSUE THREAD

**Issue by atieq-rehman-confiz** [GetStream/stream-php#67]
here is the data being posted to updateActivities() method [which is exactly same when new activity is added]

(
    [actor] => admin
    [verb] => content_published
    [object] => Post: Grading Go Bags
    [title] => Grading Go Bags
    [started_at] => Array
        (
            [date] => 2018-08-08 13:42:21.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [status] => new status on activity update is published
    [content_url] => This is test url to see if activity can be updated using this way.
    [time] => 2018-07-23 14:30:16
    [meta] => Array
        (
            [post_type] => post
            [excerpt] => The quality of earthquake survival kits ranges from solid to shaky. We rated several emergency kits on the market to find the survival bag most likely to come in handy when The Big One hits. 
            [category] => TOOLS
            [story_headline] => Getting Ready for the Big One
            [deck_headline] => The quality of earthquake survival kits ranges from solid to shaky
            [author] => Beth Spotswood
            [thumbnail] => Array
                (
                    [url] => http://localhost/altaonline.com/wp-content/uploads/2018/06/ATA050118starwars_img01.jpg
                    [alt] => 
                )

        )

    [foreign_id] => 3798
)

and it says 'Invalid JSON Payload with following trace

> PHP Fatal error:  Uncaught exception 'GetStream\Stream\StreamFeedException' with message '{"detail":"Invalid JSON payload","status_code":400,"code":4,"exception":"InputException","duration":"0.14ms"}' in C:\wamp64\www\altaonline.com\wp-content\plugins\feed-manager\vendor\get-stream\stream\lib\GetStream\Stream\Feed.php:100

**Comment by tbarbugli** [comment]
@ruggi can you reproduce this? (current test coverage for updateActivities is quite limited)

**Comment by ruggi** [comment]
@tbarbugli my PHP is quite rusty, but

```php
$activity = [
    'actor' => 'admin',
    'verb' => 'content_published',
    'object' => 'Post: Grading Go Bags',
    'title' => 'Grading Go Bags',
    'started_at' => Array
        (
            'date' => '2018-08-08 13:42:21.000000',
            'timezone_type' => '3',
            'timezone' => 'UTC',
        ),
    'status' => 'new status on activity update is published',
    'content_url' => 'This is test url to see if activity can be updated using this way.',
    'time' => '2018-07-23 14:30:16',
    'meta' => Array
        (
            'post_type' => 'post',
            'excerpt' => 'The quality of earthquake survival kits ranges from solid to shaky. We rated several emergency kits on the market to find the survival bag most likely to come in handy when The Big One hits. ',
            'category' => 'TOOLS',
            'story_headline' => 'Getting Ready for the Big One',
            'deck_headline' => 'The quality of earthquake survival kits ranges from solid to shaky',
            'author' => 'Beth Spotswood',
            'thumbnail' => Array
                (
                    'url' => 'http://localhost/altaonline.com/wp-content/uploads/2018/06/ATA050118starwars_img01.jpg',
                    'alt' => '',
                )
        ),
    'foreign_id' => '3798',
];

$feed->addActivity($activity);
// ...
$client->updateActivity($activity);
// ...
```

is working fine for me. Could you give us some more info about how the activity object is built @atieq-rehman-confiz ?

**Comment by atieq-rehman-confiz** [comment]
my usecase is as follow;
1. i create prepare activity data on post publish in wordpress using $stream_client->addActivity()
2. same activity data is converted to standard json and saved in database
3. in case of post update i extract activity data from database and decode to php 
4. then call $stream_client->updateActivities();

the snapshot of activity data of new & update post is compared and it looks exactly same.

**Comment by atieq-rehman-confiz** [comment]
// load from db
$activity = get_post_meta($post->ID, 'feed_activity', true);
//decode
$activity = json_decode($activity, true);
//update
 $activity['status'] = $status;
//save
$stream->updateActivities($existing_activity);

**Comment by ruggi** [comment]
Most likely the problem is that the API is requiring an array of activities to update, while you're probably providing only one. With the PHP client you can use the `updateActivity` method if you're providing a single activity, (or just pass an array with size 1, being your activity, to the updateActivities method) ;)

**Comment by atieq-rehman-confiz** [comment]
Got it fixed, @ruggi is correct, input was wrong for `updateActivities` method. I used other method `updateActivity()` and it worked correctly. thanks for the help
