### ISSUE TITLE
Feed slug validation is not consistent with GetStream docs

### ISSUE THREAD

**Issue by oytuntez** [GetStream/stream-php#79]
I am getting a feed_slug validation error with this slug: "user-aggregated".

I was able to create this feed from the dashboard and the docs don't mention much about the naming convention.

Issue at: `BaseFeed::validFeedSlug`

Exception received: `StreamFeedException(feed_slug can only contain alphanumeric characters or underscores)`

**Comment by ferhatelmas** [comment]
Dash is fine for feed id but not for feed type slug.

That's why `validFeedSlug` (for feed type) is correct, which you created in dashboard (because there is no API support to create it from SDK). The other one is `validUserId` (for feed id), where you're creating from SDK.
