### ISSUE TITLE
Batcher unfollowMany results in 429 Too Many Requests

### ISSUE THREAD

**Issue by TheBabaYaga** [GetStream/stream-php#81]
Client error: `POST https://api.stream-io-api.com/api/v1.0/unfollow_many/?api_key=xxxxxxx` resulted in a `429 Too Many Requests` 

response:

`{
	"detail": "Too many requests, check response headers for more information.",
	"status_code": 429,
	"code": 9,
	"exception ": "RateLimitReached",
	"duration ": "0.00 ms "
}`

I see that the REST Documentation does not have the `v1.0/unfollow_many` documented. I assume this API endpoint was implemented but has been removed again?

https://github.com/GetStream/stream-php/blob/master/lib/GetStream/Stream/Batcher.php#L91

**Comment by ferhatelmas** [comment]
Nope, it requires a paid account. If needed, contact support to add enough limiting into your app.
