### ISSUE TITLE
Add interfaces for the Feed and the Client

### ISSUE THREAD

**Issue by olix21** [GetStream/stream-php#82]
Hi,

I think it should be a great idea to implements interfaces in this project. 
We are using the SDK in Symfony, and we are trying to cover our code with some behat tests.
By implementing some interfaces, I could be able to create Dummies of the Feed and the Client objects in my tests.

I Can do a PR for that, do you have any good practice for that? Naming conventions, specific namespace?
I'm also wondering why all the methods are public? Some of them seem to be internal and should be protected/private, no?

**Comment by tbarbugli** [comment]
@olix21 I like your idea of adding interfaces to make testing easier, PRs for that are very welcome :)

We don't have a formal definition for naming conventions but the package is pretty consistent (and small) so that should be fairly easy.
