### ISSUE TITLE
Replace abandoned packages

### ISSUE THREAD

**Issue by olix21** [GetStream/stream-php#83]
Hi,

I see that this project is using 3 abandoned packages:

- `phpunit/phpunit-mock-objects`
- `guzzle/guzzle`
- `satooshi/php-coveralls`

Do you plan to upgrade those dependencies? Do you need help with that?

**Comment by tbarbugli** [comment]
wow did not know guzzle was abandoned, what do you suggest we replace that with?

**Comment by olix21** [comment]
2 packages have moved, 1 has no suggested replacement

> Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

> Package satooshi/php-coveralls is abandoned, you should avoid using it. Use php-coveralls/php-coveralls instead.

I guess using `guzzlehttp/guzzle` instead of `guzzle/guzzle` should do the trick

**Comment by pterk** [comment]
@olix21 Thanks for reporting the issue. Some upgrades were released some time ago. I'm closing this.
