### ISSUE TITLE
Use of undefined constant VERSION

### ISSUE THREAD

**Issue by kevin-lot** [GetStream/stream-php#97]
Running getstream with Symfony 5.2 on PHP 7.4.

This notice appears frequently:

`NOTICE: PHP message: PHP Warning: Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in /srv/http/vendor/get-stream/stream/lib/GetStream/Stream/Feed.php on line 67`

Best regards.

gz#10568

**Comment by ferhatelmas** [comment]
@kevin-lot what is the version of the SDK you're using?

**Comment by kevin-lot** [comment]
We are using get-stream/stream 4.1.1.

**Comment by ferhatelmas** [comment]
@kevin-lot I believe it's fixed on master, will do a release today.

**Comment by kevin-lot** [comment]
@ferhatelmas Sorry, we still have this issue. Even after the last update.

**Comment by kevin-lot** [comment]
@ferhatelmas I did that https://github.com/GetStream/stream-php/pull/102

**Comment by ferhatelmas** [comment]
Class based approach definitely will work. Thanks for preparing a PR :+1:
